### ISSUE TITLE
Docker APP_CONFIG data directory

### ISSUE THREAD

**Issue by thesysadm** [MediaBrowser/Emby.Build#57]
When running under Docker without executing the install, support a relocatable Emby data directory in "01-conf-onetime". This would more closely align with documentation at https://github.com/MediaBrowser/Wiki/wiki/Docker-Getting-Started which implies this is supported.

Reading of https://hub.docker.com/r/emby/embyserver/, however, implies that it isn't supported.

**Comment by thesysadm** [comment]
#58

**Comment by hurricanehrndz** [comment]
We use to support other data directories other than "/config" , but we never found a situation why we would to change were data is within the container. Most people want the data to be persist so they present a volume to the container which doesn't not have to mirror the container. We can definitely support that, I'm just wondering why it would be useful. There is currently lots of changes happening to the containers so not all documentation is in sync.

**Comment by thesysadm** [comment]
My primary use case is CoreOS (Docker) when not employing the instl option. Without a relocatable data directory, I'm unable to have all NFS mounted data under "/opt/data/nfs/" in the container. Instead, media would be passed as a volume there while config data would be elsewhere. It throws off using a 1:1 volume map from CoreOS to container.

**Comment by hurricanehrndz** [comment]
@thesysadm 

Fair enough. Unfortunately your pull request is not enough. In order to support one to one without breakage I need to support it in the wrapper script otherwise documentation becomes confusing. I believe the best way to do this is to add a new environment variable called `APP_GCONFIG`. That will represent the guest app config location. I will try and get the code complete within the week. If you still wish to work on it, please let me know and I will update the repo before you proceed. I have restructured my local copy to eliminate some of the redundancy.

**Comment by hurricanehrndz** [comment]
@thesysadm 
Images have been updated to support APP_GCONFIG variable. Please read the readme.
